### ISSUE TITLE
Add this project to the Sonatype Nexus Exchange

### ISSUE THREAD

**Issue by DarthHater** [savoirfairelinux/ansible-nexus3-oss#16]
Helllllo,

I'd like to add this project to our Exchange of Nexus Repo fun times functionality. It's a little hard figuring out who has ownership, etc...

http://exchange.sonatype.com/contribute?hsCtaTracking=482c6312-9301-4465-9bf3-0107abac4a3f%7Cdcaa26e5-4e3e-42e9-b324-cc1fdff431dd

Can someone on the team of awesome people who worked on this fill this out for us? I mainly just need to figure out who or what org to credit.

Thanks for doing something awesome with Nexus Repo, PS!

**Comment by samherve** [comment]
Hi @DarthHater , I just filled-in the form on your site. As of who to credit, the majority of the code comes from Savoir-faire Linux Inc. , with external contributions listed here : https://github.com/savoirfairelinux/ansible-nexus3-oss/graphs/contributors

**Comment by DarthHater** [comment]
Awesome, I added it here: http://exchange.sonatype.com/details?extension=5253002026
