### ISSUE TITLE
Adding a Docker hosted & proxy repositories

### ISSUE THREAD

**Issue by hagzag** [savoirfairelinux/ansible-nexus3-oss#2]
HI @samherve I wanted to continue your work and perhaps add more repository types to the mix especially Docker - any idea on how to do the similar conf like the maven repos ?
The only caveat I had in mind was that nexus will also need to be configured with SSL ... { we can go with self-singed at first }

I already forked your repo ;), a finger in the Docker direction via the nexus API would be good (googled it with no luck ...)

**Comment by samherve** [comment]
Hi @hagzag , to add a new repo type you would have to add some groovy script, similar to those at `templates/groovy/create_repo_maven_*.groovy` .

Unfortunately, the Nexus API is not really documented, so you can either debug a running nexus instance, or have a look at the AJAX requests that the web UI makes (with firebug for ex.). Also you can import this project in a Maven-compatible IDE (IntelliJ works fine) to have groovy scripts completion.

As for the SSL configuration, there is already a (simplistic) provisionning with HTTPD and the role vars 

```
httpd_setup_enable: true
httpd_ssl_certificate_file: 'files/nexus.vm.crt'
httpd_ssl_certificate_key_file: 'files/nexus.vm.key'
```

Please let me know if I can be of any further help
