### ISSUE TITLE
Configure HTTP(S) proxy configuration via API

### ISSUE THREAD

**Issue by dannyk81** [savoirfairelinux/ansible-nexus3-oss#20]
First of all, thanks for this! 👍 

I was wondering if the API provides a way to configure HTTP(S) proxies to be used by the Nexus instance. 

We currently configure it manually, but would be nice if we could control it centrally.

**Comment by dannyk81** [comment]
(face-palm)... I see that https://github.com/savoirfairelinux/ansible-nexus3-oss/pull/19 attempts to provide this, hope we can make this work.

**Comment by zeitounator** [comment]
I fixed this at work yesterday and provided a pull request (#21) last night..... before I saw there was one there already.... Similar approach on both.

**Comment by dannyk81** [comment]
@samherve any plan to merge #19 or this one?

**Comment by samherve** [comment]
It's on my todo list early this week to go through all the PRs !

**Comment by dannyk81** [comment]
Thank you :) closing this now.
