### ISSUE TITLE
Nexus 3.8 support

### ISSUE THREAD

**Issue by DarthHater** [savoirfairelinux/ansible-nexus3-oss#39]
Hi there!

For Nexus Repository 3.8, the url for the provisioning API is going to be changing.

You can get more information here: https://issues.sonatype.org/browse/NEXUS-14940

This is a kind heads up for y'all, thanks for the cool work you've done in making this!

Jeffry

**Comment by zeitounator** [comment]
Hi @DarthHater,

The role in this repository is not maintained anymore. See #36 and #38.

You can access a fork (which already includes all the left over pull requests of this repos and much more) here: https://github.com/ansible-ThoTeam/nexus3-oss

We already have an issue tracking the future API changes your reported here: https://github.com/ansible-ThoTeam/nexus3-oss/issues/14

Cheers.

**Comment by zeitounator** [comment]
Hi @DarthHater 

Just to let you know we released the latest version of the above mentioned role with nexus 3.8 support.

https://github.com/ansible-ThoTeam/nexus3-oss/releases/tag/v2.1

Cheers

**Comment by DarthHater** [comment]
Rad! I'll close this as a result!
